spring:
  profiles:
    active: dev
    include: secret
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.example.project1: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
    org.hibernate.orm.jdbc.extract: DEBUG
    org.springframework.transaction.interceptor: DEBUG